name: py
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - jupyter=1.0.0
  - biopython=1.79
  - cutadapt=3.5
  - gffutils=0.10.1
  - gitpython=3.1.26
  - h5py=3.6.0
  - nextflow=21.10.6
  - pandas=1.4.0
  - pycodestyle=2.8.0
  - pylint=2.12.2
  - pysam=0.17.0
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - pyyaml=6
  - samtools=1.14
  - sphinx=4.4.0
  - umi_tools=1.1.2