---
version: 1
disable_existing_loggers: False
formatters:
  standard:
    format: "%(asctime)s:%(name)s:%(levelname)s: %(message)s"
  command-line:
    format: "%(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: command-line
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: riboviz.log
    encoding: utf8
    delay: True
  timestamp_file_handler:
    class: riboviz.logging_utils.TimestampedFileHandler
    level: INFO
    formatter: standard
    prefix: riboviz.
    suffix: .log
    encoding: utf8
    delay: True
root:
  level: INFO
  handlers: [file_handler]
