"""
RiboViz workflow R-related constants, types and functions.
"""

BAM_TO_H5_R = "bam_to_h5.R"
""" Name of bam_to_h5.R script """
GENERATE_STATS_FIGS_R = "generate_stats_figs.R"
""" Name of generate_stats_figs.R script """
COLLATE_TPMS_R = "collate_tpms.R"
""" NAme of collate_tpms.R script """

THREE_NT_PERIODICITY_TSV = "3nt_periodicity.tsv"
""" File output by generate_stats_figs.R """
THREE_NT_PERIODICITY_PDF = "3nt_periodicity.pdf"
""" File output by generate_stats_figs.R """
READ_LENGTHS_TSV = "read_length.tsv"
""" File output by generate_stats_figs.R """
READ_LENGTHS_PDF = "read_length.pdf"
""" File output by generate_stats_figs.R """
POS_SP_NT_FREQ_TSV = "pos_sp_nt_freq.tsv"
""" File output by generate_stats_figs.R """
POS_SP_RPF_NORM_READS_TSV = "pos_sp_rpf_norm_reads.tsv"
""" File output by generate_stats_figs.R """
POS_SP_RPF_NORM_READS_PDF = "pos_sp_rpf_norm_reads.pdf"
""" File output by generate_stats_figs.R """
FEATURES_PDF = "features.pdf"
""" File output by generate_stats_figs.R """
TPMS_TSV = "tpms.tsv"
""" File output by generate_stats_figs.R """
CODON_RIBODENS_TSV = "codon_ribodens.tsv"
""" File output by generate_stats_figs.R """
CODON_RIBODENS_PDF = "codon_ribodens.pdf"
""" File output by generate_stats_figs.R """
START_CODON_RIBOGRID_BAR_PDF = "startcodon_ribogridbar.pdf"
""" File output by generate_stats_figs.R """
START_CODON_RIBOGRID_PDF = "startcodon_ribogrid.pdf"
""" File output by generate_stats_figs.R """
THREE_NT_FRAME_BY_GENE_TSV = "3ntframe_bygene.tsv"
""" File output by generate_stats_figs.R """
THREE_NT_FRAME_PROP_BY_GENE_PDF = "3ntframe_propbygene.pdf"
""" File output by generate_stats_figs.R """

TPMS_COLLATED_TSV = "TPMs_collated.tsv"
""" File output by collate_tpms.R """
