"""
R-related constants, types and functions.

This includes the names of R scripts used by the workflow and the
default file names output by these scripts.
"""

BAM_TO_H5_R = "bam_to_h5.R"
""" ``bam_to_h5.R`` script. """
GENERATE_STATS_FIGS_R = "generate_stats_figs.R"
""" ``generate_stats_figs.R`` script. """
COLLATE_TPMS_R = "collate_tpms.R"
""" ``collate_tpms.R`` script. """

METAGENE_START_STOP_READ_COUNTS_TSV = "metagene_start_stop_read_counts.tsv"
""" ``generate_stats_figs.R`` output file. """
METAGENE_START_STOP_READ_COUNTS_PDF = "metagene_start_stop_read_counts.pdf"
""" ``generate_stats_figs.R`` output file. """
READ_LENGTHS_TSV = "read_lengths.tsv"
""" ``generate_stats_figs.R`` output file. """
READ_LENGTHS_PDF = "read_lengths.pdf"
""" ``generate_stats_figs.R`` output file. """
POS_SP_NT_FREQ_TSV = "pos_sp_nt_freq.tsv"
""" ``generate_stats_figs.R`` output file. """
METAGENE_NORMALIZED_PROFILE_START_STOP_TSV = "metagene_normalized_profile_start_stop.tsv"
""" ``generate_stats_figs.R`` output file. """
METAGENE_NORMALIZED_PROFILE_START_STOP_PDF = "metagene_normalized_profile_start_stop.pdf"
""" ``generate_stats_figs.R`` output file. """
FEATURES_PDF = "features.pdf"
""" ``generate_stats_figs.R`` output file. """
TPMS_TSV = "tpms.tsv"
""" ``generate_stats_figs.R`` output file. """
CODON_RIBODENS_TSV = "codon_ribodens.tsv"
""" ``generate_stats_figs.R`` output file. """
CODON_RIBODENS_PDF = "codon_ribodens.pdf"
""" ``generate_stats_figs.R`` output file. """
START_CODON_RIBOGRID_BAR_PDF = "startcodon_ribogridbar.pdf"
""" ``generate_stats_figs.R`` output file. """
START_CODON_RIBOGRID_PDF = "startcodon_ribogrid.pdf"
""" ``generate_stats_figs.R`` output file. """
THREE_NT_FRAME_BY_GENE_TSV = "3ntframe_bygene.tsv"
""" ``generate_stats_figs.R`` output file. """
THREE_NT_FRAME_PROP_BY_GENE_PDF = "3ntframe_propbygene.pdf"
""" ``generate_stats_figs.R`` output file. """
THREE_NT_FRAME_BY_GENE_FILTERED_TSV = "3ntframe_bygene_filtered.tsv"
""" ``generate_stats_figs.R`` output file. """
SEQUENCE_FEATURES_TSV = "sequence_features.tsv"
""" ``generate_stats_figs.R`` output file. """
GENE_POSITION_LENGTH_COUNTS_TSV = "gene_position_length_counts_5start.tsv"
""" ``generate_stats_figs.R`` output file. """
CODON_RIBODENS_GATHERED_TSV = "codon_ribodens_gathered.tsv"
""" ``generate_stats_figs.R`` output file. """

TPMS_ALL_CDS_ALL_SAMPLES_TSV = "TPMs_all_CDS_all_samples.tsv"
""" ``collate_tpms.R`` output file. """
