"""
R-related constants, types and functions.

This includes the names of R scripts used by the workflow and the
default file names output by these scripts.
"""

BAM_TO_H5_R = "bam_to_h5.R"
""" ``bam_to_h5.R`` script. """
GENERATE_STATS_FIGS_R = "generate_stats_figs.R"
""" ``generate_stats_figs.R`` script. """
COLLATE_TPMS_R = "collate_tpms.R"
""" ``collate_tpms.R`` script. """

METAGENE_START_STOP_READ_COUNTS_TSV = "metagene_start_stop_read_counts.tsv"
""" ``generate_stats_figs.R`` output file. """
METAGENE_START_STOP_READ_COUNTS_PDF = "metagene_start_stop_read_counts.pdf"
""" ``generate_stats_figs.R`` output file. """
READ_LENGTHS_TSV = "read_lengths.tsv"
""" ``generate_stats_figs.R`` output file. """
READ_LENGTHS_PDF = "read_lengths.pdf"
""" ``generate_stats_figs.R`` output file. """
POS_SP_NT_FREQ_TSV = "pos_sp_nt_freq.tsv"
""" ``generate_stats_figs.R`` output file. """
METAGENE_NORMALIZED_PROFILE_START_STOP_TSV = "metagene_normalized_profile_start_stop.tsv"
""" ``generate_stats_figs.R`` output file. """
METAGENE_NORMALIZED_PROFILE_START_STOP_PDF = "metagene_normalized_profile_start_stop.pdf"
""" ``generate_stats_figs.R`` output file. """
ORF_TPMS_VS_FEATURES_PDF = "ORF_TPMs_vs_features.pdf"
""" ``generate_stats_figs.R`` output file. """
TPMS_TSV = "tpms.tsv"
""" ``generate_stats_figs.R`` output file. """
NORMALIZED_DENSITY_APESITES_PER_CODON_TSV = "normalized_density_APEsites_per_codon.tsv"
""" ``generate_stats_figs.R`` output file. """
NORMALIZED_DENSITY_APESITES_PER_CODON_PDF = "normalized_density_APEsites_per_codon.pdf"
""" ``generate_stats_figs.R`` output file. """
METAGENE_START_BARPLOT_BY_LENGTH_PDF = "metagene_start_barplot_by_length.pdf"
""" ``generate_stats_figs.R`` output file. """
METAGENE_START_RIBOGRID_BY_LENGTH_PDF = "metagene_start_ribogrid_by_length.pdf"
""" ``generate_stats_figs.R`` output file. """
THREE_NT_FRAME_BY_GENE_TSV = "3ntframe_bygene.tsv"
""" ``generate_stats_figs.R`` output file. """
FRAME_PROPORTIONS_PER_ORF_PDF = "frame_proportions_per_ORF.pdf"
""" ``generate_stats_figs.R`` output file. """
READ_FRAME_PER_ORF_FILTERED_TSV = "read_frame_per_ORF_filtered.tsv"
""" ``generate_stats_figs.R`` output file. """
ORF_TPMS_VS_FEATURES_TSV = "ORF_TPMs_vs_features.tsv"
""" ``generate_stats_figs.R`` output file. """
GENE_POSITION_LENGTH_COUNTS_TSV = "gene_position_length_counts_5start.tsv"
""" ``generate_stats_figs.R`` output file. """
NORMALIZED_DENSITY_APESITES_PER_CODON_LONG_TSV = "normalized_density_APEsites_per_codon_long.tsv"
""" ``generate_stats_figs.R`` output file. """

TPMS_ALL_CDS_ALL_SAMPLES_TSV = "TPMs_all_CDS_all_samples.tsv"
""" ``collate_tpms.R`` output file. """
