source("https://bioconductor.org/biocLite.R")
biocLite("Rsamtools", lib=Sys.getenv("R_LIBS_USER"))
biocLite("rhdf5", lib=Sys.getenv("R_LIBS_USER"))
biocLite("rtracklayer", lib=Sys.getenv("R_LIBS_USER"))
install.packages("RcppRoll", lib=Sys.getenv("R_LIBS_USER"))
install.packages("optparse", lib=Sys.getenv("R_LIBS_USER"))
install.packages("tidyr", lib=Sys.getenv("R_LIBS_USER"))
install.packages("ggplot2", lib=Sys.getenv("R_LIBS_USER"))
install.packages("shiny", lib=Sys.getenv("R_LIBS_USER"))
install.packages("plotly", lib=Sys.getenv("R_LIBS_USER"))
