r = getOption("repos")
r["CRAN"] = "https://cloud.r-project.org" 
options(repos = r)
dir.create(path = Sys.getenv("R_LIBS_USER"), showWarnings=FALSE, recursive=TRUE)
install.packages("RcppRoll", lib=Sys.getenv("R_LIBS_USER"))
install.packages("git2r", lib=Sys.getenv("R_LIBS_USER"))
install.packages("here", lib=Sys.getenv("R_LIBS_USER"))
install.packages("knitr", lib=Sys.getenv("R_LIBS_USER"))
install.packages("optparse", lib=Sys.getenv("R_LIBS_USER"))
install.packages("plotly", lib=Sys.getenv("R_LIBS_USER"))
install.packages("rmarkdown", lib=Sys.getenv("R_LIBS_USER"))
install.packages("shiny", lib=Sys.getenv("R_LIBS_USER"))
install.packages("tidyverse", lib=Sys.getenv("R_LIBS_USER"))
install.packages("BiocManager")
BiocManager::install("Rsamtools", lib=Sys.getenv("R_LIBS_USER"))
BiocManager::install("rtracklayer", lib=Sys.getenv("R_LIBS_USER"))
BiocManager::install("rhdf5", lib=Sys.getenv("R_LIBS_USER"))
BiocManager::install("ShortRead", lib=Sys.getenv("R_LIBS_USER"))
# Developer dependencies
install.packages("devtools", lib=Sys.getenv("R_LIBS_USER"))
install.packages("glue", lib=Sys.getenv("R_LIBS_USER"))
install.packages("lintr", lib=Sys.getenv("R_LIBS_USER"))
install.packages("roxygen2", lib=Sys.getenv("R_LIBS_USER"))
install.packages("styler", lib=Sys.getenv("R_LIBS_USER"))
install.packages("testthat", lib=Sys.getenv("R_LIBS_USER"))
install.packages("withr", lib=Sys.getenv("R_LIBS_USER"))
